### ISSUE TITLE
Upgrade Terraform version to v1.6.x for tf-runner

### ISSUE THREAD

**Issue by tao-zhang-shell** [flux-iac/tofu-controller#1294]
I see TF version has been upgraded to [v1.5.7](https://github.com/flux-iac/tofu-controller/blob/9bab501e092c467a55eec7f546ff9d412fcab8ac/runner.Dockerfile#L5C1-L5C21) in ToFu controller release v0.16.0-rc4.

However, I need some fix in Terraform v1.6.x. Can you please upgrade TF version to v1.6.x?

**Comment by krone-rose** [comment]
Without involved to the project and the discussions in the background, I think the Hashicorp Terraform License change (https://www.doppler.com/blog/what-the-terraform-license-change-means-for-devops) makes this impossible without legal topic/problems

Currently I think this project moves strong to OpenTofu.

Disclaimer I'm not a project member this is only my opinion to this topic.

**Comment by tao-zhang-shell** [comment]
Thank you @krone-rose , I'm also aware of that. I think Terraform v1.5.x is the last version under MPL licence. 

So the question is, what's the roadmap of tf-runner in the future?

**Comment by ilithanos** [comment]
The current roadmap is mainly focusing on getting native openTofu support, but keeping support for the latest MPL licensed version of the hashicorp terraform as well.

The license change blocks us from upgrading due to legal concerns.

It is possible to build a custom runner image yourself, and include the updated terraform binary and it should work, but we can't officially support it.

**Comment by akselleirv** [comment]
Closing as completed. Please reopen if needed.
